### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ashwin153** [wager/hub#61]
- [x] When you schedule a task, you have to specify all the fields even if you're updating just one of them. Why not describe the current version, modify some of its attributes, and then schedule the modified version.
- [x] It's really hard to get the logs for a run. Part of the problem is that the job names are really opaque. Maybe the logs or at the very least a link to the logs (Google Cloud Logging query for the run id label?) should be displayed when monitoring a run. 
- [ ] None of the applications deployed to Kubernetes specify resources.
- [x] None of the jobs deployed to Kubernetes specify resources.
- [ ] It would be nice for GitHub Actions and Terraform Cloud failures to flow into PagerDuty. One idea is to use Cloudflare Email Routing to fool the email verification system; redirect emails to a personal account to verify them and then change the redirection to PagerDuty to trigger alerts. Another idea is to use Prometheus exporters and alerts on the exported metrics.
- [ ] It would be nice to have some visibility into slow database queries so that the necessary indices can be created. This can be done by setting the `log_duration` and `log_min_duration_statement` database flags on the Cloud SQL instance and verifying that the information flows through to Google Cloud Logging (by temporarily setting `log_min_duration_statement` to `0`).

**Comment by ashwin153** [comment]
```python
import pendulum
import webbrowser
    
@scheduler.command()
@click.option(
    "--name",
    cls=OneOf,
    variants=["run-id", "task-id"],
    type=str,
    help="Name of the task to monitor.")
@click.option(
    "--namespace",
    cls=OneOf,
    variants=["run-id", "task-id"],
    type=str,
    help="Namespace of the task to monitor.")
@click.option(
    "--run-id",
    cls=OneOf,
    variants=["task-id", "namespace", "name"],
    type=str,
    help="Identifier of the run to monitor.")
@click.option(
    "--task-id",
    cls=OneOf,
    variants=["run-id", "namespace", "name"],
    type=str,
    help="Identifier of the task to monitor.")
@click.pass_obj
def logs(
    scheduler: Scheduler,
    name: Optional[str],
    namespace: Optional[str],
    run_id: Optional[str],
    task_id: Optional[str],
) -> None:
    """Monitor the status of a run."""
    if run_id is not None:
        run = Run.Selector(id=uuid.UUID(run_id))
    elif task_id is not None:
        run = Run.Selector(task=Task.Selector(id=uuid.UUID(task_id)))
    elif namespace is not None and name is not None:
        run = Run.Selector(task=Task.Selector(group=Task.Group(namespace=namespace, name=name)))
    else:
        raise ValueError("One of --run-id, --task-id, or --namespace and --name must be specified.")

    status = scheduler.monitor(run)

    webbrowser.open("".join([
        "https://console.cloud.google.com/logs/query"
        f";query=labels.%22k8s-pod%2Fjob-name%22%3Dparlay-executor-{status.run.id}"
        f";timeRange={status.started.isoformat()}%2F{pendulum.now().isoformat()}"
        "?project=wager-233003"
    ]))
```
